---
name: WordPress CI/CD Deploy

on:
  push:
    branches:
      - dev
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Ensure zip/unzip installed
        run: sudo apt-get update && sudo apt-get install -y zip unzip

      - name: Prepare WordPress Zip
        run: |
          WP_LINK=$(cat wp-version-control.cfg)
          wget -O "./wordpress.zip" $WP_LINK

      - name: Prepare plugins and theme zip
        run: zip -r wpcontent.zip plugins mu-plugins themes

      - name: List workspace contents before SCP
        run: ls -lhA

      - name: Copy Zips to Server (Dev)
        if: github.event_name == 'push'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: |
            ./wordpress.zip
            ./wpcontent.zip
          target: /var/www/playstore/dev/html

      - name: Copy Zips to Server (Prod)
        if: github.event_name == 'release'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: |
            ./wordpress.zip
            ./wpcontent.zip
          target: /var/www/playstore/prod/html

      - name: Enable Maintenance Mode (Dev)
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            echo "<?php \$upgrading = time(); ?>" > /var/www/playstore/dev/html/.maintenance

      - name: Enable Maintenance Mode (Prod)
        if: github.event_name == 'release'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            echo "<?php \$upgrading = time(); ?>" > /var/www/playstore/prod/html/.maintenance

      - name: Update WordPress Core (Dev)
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            # Remove all PHP files except wp-config.php
            find /var/www/playstore/dev/html -type f -name "*.php" ! -name "wp-config.php" -delete
            # Remove wp-includes
            rm -rf /var/www/playstore/dev/html/wp-includes
            # Unzip new WordPress core
            unzip -o /var/www/playstore/dev/html/wordpress.zip -d /var/www/playstore/dev/html
            # Remove wordpress.zip
            rm -f /var/www/playstore/dev/html/wordpress.zip

      - name: Update WordPress Core (Prod)
        if: github.event_name == 'release'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            # Remove all PHP files except wp-config.php
            find /var/www/playstore/prod/html -type f -name "*.php" ! -name "wp-config.php" -delete
            # Remove wp-includes
            rm -rf /var/www/playstore/prod/html/wp-includes
            # Unzip new WordPress core
            unzip -o /var/www/playstore/prod/html/wordpress.zip -d /var/www/playstore/prod/html
            # Remove wordpress.zip
            rm -f /var/www/playstore/prod/html/wordpress.zip

      - name: Update Plugins and Theme (Dev)
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            # Remove old content
            rm -rf /var/www/playstore/dev/html/wp-content/plugins
            rm -rf /var/www/playstore/dev/html/wp-content/themes
            rm -rf /var/www/playstore/dev/html/wp-content/mu-plugins
            # Unzip new plugins and themes
            unzip -o /var/www/playstore/dev/html/wpcontent.zip -d /var/www/playstore/dev/html/wp-content
            # Remove wpcontent.zip
            rm -f /var/www/playstore/dev/html/wpcontent.zip

      - name: Update Plugins and Theme (Prod)
        if: github.event_name == 'release'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            # Remove old content
            rm -rf /var/www/playstore/prod/html/wp-content/plugins
            rm -rf /var/www/playstore/prod/html/wp-content/themes
            rm -rf /var/www/playstore/prod/html/wp-content/mu-plugins
            # Unzip new plugins and themes
            unzip -o /var/www/playstore/prod/html/wpcontent.zip -d /var/www/playstore/prod/html/wp-content
            # Remove wpcontent.zip
            rm -f /var/www/playstore/prod/html/wpcontent.zip

      - name: Disable Maintenance Mode and Cleanup (Dev)
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            rm -f /var/www/playstore/dev/html/.maintenance

      - name: Disable Maintenance Mode and Cleanup (Prod)
        if: github.event_name == 'release'
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            rm -f /var/www/playstore/prod/html/.maintenance
